DO $$
BEGIN
  ALTER TABLE users ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
  ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url VARCHAR(500);
  ALTER TABLE attendance ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
  ALTER TABLE attendance ADD COLUMN IF NOT EXISTS remarks TEXT;
  ALTER TABLE ratings ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
  ALTER TABLE social_tasks ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
  ALTER TABLE proof_submissions ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
  ALTER TABLE departments ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
  ALTER TABLE meetings ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
  ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS old_value JSONB;
  ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS new_value JSONB;
  ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS user_agent VARCHAR(500);
END$$;
